/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author felip
 */
public class GUI extends javax.swing.JFrame {

	/**
 	* Crear el GUI
 	*/
	public GUI() {
    	initComponents();
	}

	/**
 	* This method is called from within the constructor to initialize the form.
 	* WARNING: Do NOT modify this code. The content of this method is always
 	* regenerated by the Form Editor.
 	*/
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

    	Divicion = new javax.swing.ButtonGroup();
    	jLabel1 = new javax.swing.JLabel();
    	Nombre = new javax.swing.JTextField();
    	jLabel2 = new javax.swing.JLabel();
    	jLabel3 = new javax.swing.JLabel();
    	Apellido = new javax.swing.JTextField();
    	Sumitt = new javax.swing.JButton();
    	jLabel5 = new javax.swing.JLabel();
    	jLabel6 = new javax.swing.JLabel();
    	jLabel7 = new javax.swing.JLabel();
    	jLabel8 = new javax.swing.JLabel();
    	Contraseña = new javax.swing.JTextField();
    	Correo = new javax.swing.JTextField();
    	Extencion = new javax.swing.JTextField();
    	jRadioButton1 = new javax.swing.JRadioButton();
    	jRadioButton2 = new javax.swing.JRadioButton();
    	jRadioButton3 = new javax.swing.JRadioButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    	setBackground(new java.awt.Color(139, 198, 140));

    	jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
    	jLabel1.setText("Creacion de correos");

    	Nombre.setToolTipText("");
    	Nombre.setName("Text_1"); // NOI18N

    	jLabel2.setText("Ingresa tu nombre");

    	jLabel3.setText("Ingresa tus apellidos");

    	Apellido.setToolTipText("Ej: Perez");
    	Apellido.setName("Text_2"); // NOI18N

    	Sumitt.setText("Enter");
    	Sumitt.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
            	SumittActionPerformed(evt);
        	}
    	});

    	jLabel5.setText("Enviar datos");

    	jLabel6.setText("Capacidad");

    	jLabel7.setText("Contraseña");
    	jLabel7.setName("OutPut_1"); // NOI18N

    	jLabel8.setText("Correo");
    	jLabel8.setName("OutPut_2"); // NOI18N

    	Contraseña.setEditable(false);

    	Correo.setEditable(false);

    	Extencion.setEditable(true);

    	Divicion.add(jRadioButton1);
    	jRadioButton1.setText("Estudiante");
    	jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jRadioButton1ActionPerformed(evt);
        	}
    	});
		Divicion.add(jRadioButton2);
    	jRadioButton2.setText("Profesor");
    	jRadioButton2.setToolTipText("");
    	jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jRadioButton2ActionPerformed(evt);
        	}
    	});
		Divicion.add(jRadioButton3);
    	jRadioButton3.setText("Otro");
    	jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jRadioButton3ActionPerformed(evt);
        	}
    	});
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    	getContentPane().setLayout(layout);
    	layout.setHorizontalGroup(
        	layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        	.addGroup(layout.createSequentialGroup()
            	.addGap(24, 24, 24)
            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                	.addGroup(layout.createSequentialGroup()
                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            	.addComponent(Apellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                            	.addComponent(Nombre, javax.swing.GroupLayout.Alignment.LEADING))
                        	.addComponent(jLabel3))
                    	.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                	.addGroup(layout.createSequentialGroup()
                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        	.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        	.addComponent(jLabel2)
                        	.addGroup(layout.createSequentialGroup()
                            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                	.addComponent(jLabel5)
                                	.addComponent(Sumitt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            	.addGap(43, 43, 43)
                            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                	.addGroup(layout.createSequentialGroup()
                                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        	.addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                        	.addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                    	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        	.addComponent(Correo)
                                        	.addComponent(Extencion, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        	.addComponent(jRadioButton1)
                                        	.addComponent(jRadioButton2)
                                        	.addComponent(jRadioButton3))
                                    	.addGroup(layout.createSequentialGroup()
                                        	.addComponent(jLabel7)
                                        	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        	.addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    	.addGap(0, 70, Short.MAX_VALUE))))
    	);
    	layout.setVerticalGroup(
        	layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        	.addGroup(layout.createSequentialGroup()
            	.addGap(19, 19, 19)
            	.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            	.addGap(18, 18, 18)
            	.addComponent(jLabel2)
            	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                	.addGroup(layout.createSequentialGroup()
                    	.addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    	.addGap(18, 18, 18)
                    	.addComponent(jLabel3)
                    	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    	.addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                	.addGroup(layout.createSequentialGroup()
                    	.addComponent(jRadioButton1)
                    	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    	.addComponent(jRadioButton2)
                    	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    	.addComponent(jRadioButton3)))
            	.addGap(51, 51, 51)
            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                	.addGroup(layout.createSequentialGroup()
                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        	.addComponent(jLabel7)
                        	.addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    	.addGap(11, 11, 11)
                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        	.addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        	.addComponent(jLabel8))
                    	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        	.addComponent(Extencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        	.addComponent(jLabel6)))
                	.addGroup(layout.createSequentialGroup()
                    	.addComponent(jLabel5)
                    	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    	.addComponent(Sumitt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
            	.addContainerGap(44, Short.MAX_VALUE))
    	);
		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void SumittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumittActionPerformed
	String firstName = Nombre.getText();
	String lastName = Apellido.getText();

   
	String department = "";
	if (jRadioButton1.isSelected()) {
    	department = "estudiantes";
	} else if (jRadioButton2.isSelected()) {
    	department = "profesor";
	} else if (jRadioButton3.isSelected()) {
    	department = "";
	}

	Email email = new Email(firstName, lastName, department);

	// Generador de labels de email y contraseña 
	Correo.setText(email.getEmail());
	Contraseña.setText(email.getPassword());
	Extencion.setText("500 MB");


	}//GEN-LAST:event_SumittActionPerformed

	private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
    	// TODO add your handling code here:
	}//GEN-LAST:event_jRadioButton2ActionPerformed

	private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
    	// TODO add your handling code here:
	}//GEN-LAST:event_jRadioButton1ActionPerformed

	private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
    	// TODO add your handling code here:
	}//GEN-LAST:event_jRadioButton3ActionPerformed

	/**
 	* @param args the command line arguments
 	*/
	public static void main(String args[]) {

    	try {
        	for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            	if ("Nimbus".equals(info.getName())) {
                	javax.swing.UIManager.setLookAndFeel(info.getClassName());
                	break;
            	}
        	}
    	} catch (ClassNotFoundException ex) {
        	java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    	} catch (InstantiationException ex) {
        	java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    	} catch (IllegalAccessException ex) {
        	java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
        	java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    	}
    	//</editor-fold>

    	/* Create and display the form */
    	java.awt.EventQueue.invokeLater(new Runnable() {
        	@Override
        	public void run() {
            	new GUI().setVisible(true);
        	}
    	});
	}
// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JTextField Apellido;
private javax.swing.JTextField Contraseña;
private javax.swing.JTextField Correo;
private javax.swing.ButtonGroup Divicion;
private javax.swing.JTextField Extencion;
private javax.swing.JTextField Nombre;
private javax.swing.JButton Sumitt;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel5;
private javax.swing.JLabel jLabel6;
private javax.swing.JLabel jLabel7;
private javax.swing.JLabel jLabel8;
private javax.swing.JRadioButton jRadioButton1;
private javax.swing.JRadioButton jRadioButton2;
private javax.swing.JRadioButton jRadioButton3;
// End of variables declaration//GEN-END:variables
}


