/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Emailapp;

/**
 *
 * @author felip
 */
public class GUI extends javax.swing.JFrame {

	/**
 	* Creates new form GUI
 	*/
	public GUI() {
    	initComponents();
	}

	/**
 	* This method is called from within the constructor to initialize the form.
 	* WARNING: Do NOT modify this code. The content of this method is always
 	* regenerated by the Form Editor.
 	*/
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

    	Divicion = new javax.swing.ButtonGroup();
    	jLabel1 = new javax.swing.JLabel();
    	Nombre = new javax.swing.JTextField();
    	jLabel2 = new javax.swing.JLabel();
    	jLabel3 = new javax.swing.JLabel();
    	Apellido = new javax.swing.JTextField();
    	Sumitt = new javax.swing.JButton();
    	jLabel5 = new javax.swing.JLabel();
    	jLabel6 = new javax.swing.JLabel();
    	jLabel7 = new javax.swing.JLabel();
    	jLabel8 = new javax.swing.JLabel();
    	Contraseña = new javax.swing.JTextField();
    	Correo = new javax.swing.JTextField();
    	Extencion = new javax.swing.JTextField();
    	jRadioButton1 = new javax.swing.JRadioButton();
    	jRadioButton2 = new javax.swing.JRadioButton();
    	jRadioButton3 = new javax.swing.JRadioButton();
